wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.16.1
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718117563.173338
    t:
      1:
      - 1
      - 9
      - 41
      - 50
      - 55
      - 77
      2:
      - 1
      - 9
      - 41
      - 50
      - 55
      - 77
      3:
      - 23
      4: 3.9.16
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
